image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - before: bash gitpodSetup.sh
    init: poetry install # runs during prebuild
    command: echo "export POETRY_MODULES=$(realpath $(find $(POETRY_CACHE_DIR) -path "*/bin"))" >> /home/gitpod/.profile && echo "export PATH=$POETRY_MODULES:$PATH" >> /home/gitpod/.profile && source /home/gitpod/.profile
